# Setup
title:               'sudo learn: an educational project'
tagline:             'Free, curated and direct content for developers all around the world.'
description:         'This site was created with the objective of offering free, curated and direct information for developers all around the world.'
url:                 'https://erlete.github.io/'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Paulo Sanchez
  url:               https://github.com/erlete/
  email:             dev.szblzpaulo@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Theme
remote_theme: poole/lanyon
